dependencies:
  - conda-forge::pip=21.0.1
  - conda-forge::python=3.10
  - conda-forge::astropy=6.0.0
  - conda-forge::matplotlib=3.8.2
  - conda-forge::numpy=1.26.2
  - conda-forge::pandas=2.1.3
  - conda-forge::seaborn=0.13.0
  - conda-forge::scipy=1.11.4
  - conda-forge::hydra-core=1.3.2
  # - pip:
  #     - matplotlib==3.4.3
